# Generated by Django 4.2.4 on 2023-12-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=10, verbose_name='Максимальный балл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео пользователя',
                'verbose_name_plural': 'Все видео пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=30, verbose_name='Максимальный балл')),
                ('status', models.CharField(choices=[('START', 'Старт'), ('PROGRESS', 'В процессе'), ('CONFIRM', 'Получение оценку'), ('FINISH', 'Завершено')], default='Старт', max_length=255, verbose_name='Статус')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserQuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начинание')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Закончание')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=60, verbose_name='Максимальный балл')),
                ('status', models.CharField(choices=[('START', 'Старт'), ('PROGRESS', 'В процессе'), ('FINISH', 'Завершено')], default='Старт', max_length=255, verbose_name='Статус')),
                ('questions', models.ManyToManyField(blank=True, to='products.question', verbose_name='Вопросы')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест пользователя',
                'verbose_name_plural': 'Тесты пользователей',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_subscribe', models.BooleanField(default=False, verbose_name='Подписка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продукт пользователя',
                'verbose_name_plural': 'Продукты пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Урок пользователя',
                'verbose_name_plural': 'Уроки пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('is_subscribe', models.BooleanField(default=False, verbose_name='Подписка')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Глава пользователя',
                'verbose_name_plural': 'Главы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=1, verbose_name='Максимальный балл')),
                ('answers', models.ManyToManyField(blank=True, to='products.answer', verbose_name='Ответы пользователя')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.question', verbose_name='Вопрос')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userquizdata', verbose_name='Тест пользователя')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Продукты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
