# Generated by Django 4.2.4 on 2023-08-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начинание')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Закончание')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('questions', models.ManyToManyField(to='products.question', verbose_name='Вопросы')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест данные пользователя',
                'verbose_name_plural': 'Тесты данные пользователей',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=1, verbose_name='Максимальный балл')),
                ('answers', models.ManyToManyField(to='products.answer', verbose_name='Ответ пользователя')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.question', verbose_name='Вопрос')),
                ('user_quiz_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userquizdata', verbose_name='Тест данные пользователя')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
