# Generated by Django 4.2.4 on 2024-01-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_course_options'),
        ('profiles', '0002_profile_about_profile_is_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('poster', models.ImageField(upload_to='products/headliners/', verbose_name='Poster')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Headliner',
                'verbose_name_plural': 'Headliners',
            },
        ),
    ]
