# Generated by Django 4.2.4 on 2024-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_headliner'),
    ]

    operations = [
        migrations.AddField(
            model_name='headliner',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
    ]
