# Generated by Django 4.2.4 on 2023-09-06 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_question_body'),
        ('profiles', '0003_alter_userquizdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_created', models.BooleanField(default=False, verbose_name='Начало')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Глава пользователя',
                'verbose_name_plural': 'Главы пользователей',
            },
        ),
    ]
