# Generated by Django 4.2.4 on 2024-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_headliner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(default=1, max_length=32, verbose_name='Specialty'),
            preserve_default=False,
        ),
    ]
