# Generated by Django 4.2.4 on 2023-09-06 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_userchapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapter',
            name='is_created',
        ),
        migrations.AddField(
            model_name='userchapter',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Урок пользователя',
                'verbose_name_plural': 'Уроки пользователей',
            },
        ),
    ]
