# Generated by Django 4.2.4 on 2024-02-10 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_lesson_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_userlesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlesson',
            name='is_done',
        ),
        migrations.AddField(
            model_name='userlesson',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is_completed'),
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
