# Generated by Django 4.2.4 on 2024-02-10 02:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_lesson_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_remove_userlesson_is_done_userlesson_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseLesson',
            new_name='UserCourse',
        ),
    ]
