# Generated by Django 4.2.4 on 2023-09-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Балл'),
        ),
    ]
