# Generated by Django 4.2.4 on 2024-02-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_courselesson_usercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchapter',
            options={'verbose_name': 'User chapter', 'verbose_name_plural': 'User chapters'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': 'User course', 'verbose_name_plural': 'User courses'},
        ),
        migrations.AlterModelOptions(
            name='userlesson',
            options={'verbose_name': 'User lesson', 'verbose_name_plural': 'User lessons'},
        ),
    ]
