# Generated by Django 4.2.4 on 2023-09-08 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_question_body'),
        ('profiles', '0012_alter_userlesson_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquizdata',
            options={'ordering': ('-start_time',), 'verbose_name': 'Тест пользователя', 'verbose_name_plural': 'Тесты пользователей'},
        ),
        migrations.AddField(
            model_name='userquizdata',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='userquizdata',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Балл'),
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео пользователя',
                'verbose_name_plural': 'Все видео пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Видео пользователя',
                'verbose_name_plural': 'Все видео пользователей',
            },
        ),
    ]
