# Generated by Django 4.2.4 on 2023-09-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0013_alter_userquizdata_options_userquizdata_max_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizdata',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Тест'),
        ),
    ]
