# Generated by Django 4.2.4 on 2023-09-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_userquizdata_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapter',
            name='is_subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
