# Generated by Django 4.2.4 on 2023-09-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userchapter_is_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Задание пользователя', 'verbose_name_plural': 'Задания пользователей'},
        ),
    ]
