# Generated by Django 4.2.4 on 2023-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0016_alter_usertask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizdata',
            name='questions',
            field=models.ManyToManyField(blank=True, to='products.question', verbose_name='Вопросы'),
        ),
    ]
