# Generated by Django 4.2.4 on 2023-09-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0017_alter_userquizdata_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answers',
            field=models.ManyToManyField(blank=True, to='products.answer', verbose_name='Ответы пользователя'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_quiz_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userquizdata', verbose_name='Тест пользователя'),
        ),
    ]
