# Generated by Django 4.2.4 on 2023-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_rename_user_quiz_data_useranswer_user_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='is_done',
        ),
        migrations.AddField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('PROGRESS', 'В процессе'), ('FINISH', 'Завершено')], default='В процессе', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='userquizdata',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл'),
        ),
    ]
