# Generated by Django 4.2.4 on 2023-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_usertask_is_done_usertask_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapter',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл'),
        ),
    ]
