# Generated by Django 4.2.4 on 2023-09-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_userquizdata_max_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл'),
        ),
    ]
