# Generated by Django 4.2.4 on 2023-09-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0024_alter_usertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
    ]
