# Generated by Django 4.2.4 on 2023-09-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0025_alter_userproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Раздел'),
        ),
    ]
