# Generated by Django 4.2.4 on 2023-09-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0026_alter_userchapter_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lesson', verbose_name='Урок'),
        ),
    ]
