# Generated by Django 4.2.4 on 2023-09-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('profiles', '0027_alter_userlesson_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizdata',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.video', verbose_name='Видео'),
        ),
    ]
