# Generated by Django 4.2.4 on 2023-12-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0003_alter_institution_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Год основания'),
        ),
    ]
