# Generated by Django 4.2.4 on 2024-08-13 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('STUDENT', 'Student'), ('AUTHOR', 'Author')], default='Student', max_length=64, verbose_name='Account type')),
                ('specialty', models.CharField(blank=True, max_length=128, null=True, verbose_name='Specialty')),
                ('bio', models.TextField(blank=True, max_length=256, null=True, verbose_name='Bio')),
                ('account_fill', models.BooleanField(default=False, verbose_name='Is filled out')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
