# Generated by Django 4.2.4 on 2024-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_account_bio_kk_account_bio_ru_account_specialty_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio_en',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='account',
            name='specialty_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Specialty'),
        ),
    ]
