# Generated by Django 5.1 on 2024-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_account_bio_en_account_specialty_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('AUTHOR', 'Author')], default='STUDENT', max_length=64, verbose_name='Account type'),
        ),
    ]
