# Generated by Django 4.2.4 on 2023-10-17 12:29

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('user_type', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STUDENT', 'Студент'), ('TEACHER', 'Педагог'), ('MANAGER', 'Менеджер')], default='Не выбрано', max_length=64, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, help_text='Максимальный размер файла составляет 2 МБ', null=True, upload_to='accounts/user/image/', validators=[accounts.models.User.validate_image], verbose_name='Изображение')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Язык')),
                ('slug', models.SlugField(max_length=64, verbose_name='Ключ языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accounts/institution/images/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inst_type', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SCHOOL', 'Школа'), ('COMMUNITY', 'Сообщество')], default='Не выбрано', max_length=255, verbose_name='Тип учреждение')),
                ('ownership', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STATE', 'Государственная'), ('PRIVATE', 'Частная')], default='Не выбрано', max_length=255, verbose_name='Форма собственности')),
                ('school_view', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('GENERAL', 'Общеобразовательная'), ('LYCEUM', 'Лицей')], default='Не выбрано', max_length=255, verbose_name='Вид')),
                ('slope', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('TECH', 'Технические'), ('HUMAN', 'Гуманитарные')], default='Не выбрано', max_length=255, verbose_name='Уклон')),
                ('direction', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('IT', 'Информационные технологии'), ('GENERAL_EDU', 'Общее образование')], default='Не выбрано', max_length=255, verbose_name='Направление')),
                ('date_created', models.DateField(verbose_name='Год основания')),
                ('license_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер лиценизии')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Веб-сайт')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('ln', models.ManyToManyField(blank=True, to='accounts.language', verbose_name='Язык обучения')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('class_level', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5), ('SIX', 6), ('SEVEN', 7), ('EIGHT', 8), ('NINE', 9), ('TEN', 10), ('ELEVEN', 11)], default='Не выбрано', verbose_name='Уровень класса')),
                ('flow', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('ONE', 1), ('TWO', 2), ('THREE', 3)], default='Не выбрано', verbose_name='Поток')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institution', verbose_name='Учереждение')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Класс/Группа',
                'verbose_name_plural': 'Классы/Группы',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('gender', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('MALE', 'Ер'), ('FAMALE', 'Әйел')], default='Не выбрано', max_length=64, verbose_name='Пол')),
                ('city', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы'), ('ASTANA', 'Астана')], default='Не выбрано', max_length=64, verbose_name='Город')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('account_fill', models.BooleanField(default=False, verbose_name='Аккаунт заполнено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
