# Generated by Django 4.2.4 on 2024-08-12 19:51

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=64, verbose_name='Full name')),
                ('image', models.ImageField(blank=True, help_text='The maximum file size is 2 MB', null=True, upload_to='accounts/user/image/', validators=[accounts.models.User.validate_image], verbose_name='Image')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('NOT_DEFINED', 'Not selected'), ('MALE', 'Male'), ('FAMALE', 'Famale')], default='Not selected', max_length=64, verbose_name='Gender')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='OldAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('USER', 'User'), ('AUTHOR', 'Author'), ('LLP', 'Limited Liability Partnership')], default='User', max_length=64, verbose_name='Account type')),
                ('id_number', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID number account')),
                ('specialty', models.CharField(blank=True, max_length=64, null=True, verbose_name='Specialty')),
                ('city', models.CharField(choices=[('NOT_DEFINED', 'Not selected'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы'), ('ASTANA', 'Астана')], default='Not selected', max_length=64, verbose_name='City')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('about', models.TextField(blank=True, max_length=120, null=True, verbose_name='About')),
                ('account_fill', models.BooleanField(default=False, verbose_name='Is filled out')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Old Account',
                'verbose_name_plural': 'Old Accounts',
            },
        ),
        migrations.CreateModel(
            name='CloneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='username')),
                ('full_name', models.CharField(max_length=64, verbose_name='Full name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accounts/user/image/', verbose_name='Image')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='clone_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='clone_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Clone User',
                'verbose_name_plural': 'Clone Users',
            },
        ),
    ]
