# Generated by Django 4.2.4 on 2023-12-04 16:33

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=64, verbose_name='Полная имя')),
                ('user_type', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STUDENT', 'Студент'), ('TEACHER', 'Педагог'), ('MANAGER', 'Менеджер')], default='Не выбрано', max_length=64, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, help_text='Максимальный размер файла составляет 2 МБ', null=True, upload_to='accounts/user/image/', validators=[accounts.models.User.validate_image], verbose_name='Изображение')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('gender', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('MALE', 'Ер'), ('FAMALE', 'Әйел')], default='Не выбрано', max_length=64, verbose_name='Пол')),
                ('city', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы'), ('ASTANA', 'Астана')], default='Не выбрано', max_length=64, verbose_name='Город')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('account_fill', models.BooleanField(default=False, verbose_name='Аккаунт заполнено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
