# Generated by Django 4.2.4 on 2023-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='Программы'),
        ),
    ]
