# Generated by Django 4.2.4 on 2024-03-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
    ]
