# Generated by Django 4.2.4 on 2024-08-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloneUser',
        ),
    ]
