# Generated by Django 4.2.4 on 2024-03-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_birthday_remove_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NOT_DEFINED', 'Not selected'), ('MALE', 'Male'), ('FAMALE', 'Famale')], default='Not selected', max_length=64, verbose_name='Gender'),
        ),
    ]
