# Generated by Django 4.2.4 on 2023-08-04 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STUDENT', 'Оқушы'), ('TEACHER', 'Педагог'), ('SCHOOL', 'Білім беру мекемесі (мектеп)')], default='Не выбрано', max_length=64, verbose_name='Тип')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Тип пользователи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('MALE', 'Ер'), ('FAMALE', 'Әйел')], default='Не выбрано', max_length=64, verbose_name='gender')),
                ('area', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы')], default='Не выбрано', max_length=64, verbose_name='Область')),
                ('city', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('TURKESTAN', 'Түркістан облысы'), ('ALMATY_AREA', 'Алматы облысы')], default='Не выбрано', max_length=64, verbose_name='Город')),
                ('school', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('13-01', '№1 Алтынсарин орта мектебі'), ('13-02', '№7 Момышұлы мектебі')], default='Не выбрано', max_length=64, verbose_name='Город')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='phone')),
                ('is_profile_fill', models.BooleanField(default=False, verbose_name='Профиль заполнено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
