# Generated by Django 4.2.4 on 2024-03-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birthday_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('USER', 'User'), ('AUTHOR', 'Author'), ('LLP', 'Limited Liability Partnership')], default='User', max_length=64, verbose_name='Account type'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID number account'),
        ),
        migrations.AddField(
            model_name='account',
            name='specialty',
            field=models.CharField(default='...', max_length=32, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
    ]
