# Generated by Django 4.2.4 on 2023-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertype_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('MALE', 'Ер'), ('FAMALE', 'Әйел')], default='Не выбрано', max_length=64, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('13-01', '№1 Алтынсарин орта мектебі'), ('13-02', '№7 Момышұлы мектебі')], default='Не выбрано', max_length=64, verbose_name='Школа'),
        ),
    ]
