# Generated by Django 4.2.4 on 2024-03-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_about_account_account_type_account_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='specialty',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Specialty'),
        ),
    ]
