# Generated by Django 4.2.4 on 2023-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_birthday_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('TURKESTAN', 'Түркістан облысы'), ('ALMATY_AREA', 'Алматы облысы')], default='Не выбрано', max_length=64, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы')], default='Не выбрано', max_length=64, verbose_name='Город'),
        ),
    ]
