# Generated by Django 4.2.4 on 2023-08-12 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_profile_account_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы'), ('ASTANA', 'Астана')], default='Не выбрано', max_length=64, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inst_type', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SCHOOL', 'Школа'), ('COLLEDGE', 'Колледж')], default='Не выбрано', max_length=255, verbose_name='Тип учреждение')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Генеральный директор')),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('teachers', models.ManyToManyField(related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='Педагоги')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
            },
        ),
    ]
