# Generated by Django 4.2.4 on 2024-08-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cloneuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloneUser',
        ),
    ]
