# Generated by Django 4.2.4 on 2023-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_institution_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='school',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STUDENT', 'Оқушы'), ('TEACHER', 'Педагог'), ('MANAGER', 'Менеджер')], default='Не выбрано', max_length=64, verbose_name='Тип'),
        ),
    ]
