# Generated by Django 4.2.4 on 2023-08-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_school_alter_usertype_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_profile_fill',
            new_name='account_fill',
        ),
    ]
