# Generated by Django 4.2.4 on 2024-08-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cloneuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.cloneuser', verbose_name='User'),
        ),
    ]
