# Generated by Django 4.2.4 on 2023-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_profile'),
        ('accounts', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='Продукты'),
        ),
    ]
