# Generated by Django 4.2.4 on 2024-08-12 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cloneuser_groups_cloneuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
