# Generated by Django 4.2.4 on 2024-08-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_oldaccount_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloneUser',
        ),
    ]
