# Generated by Django 4.2.4 on 2023-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='area',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STUDENT', 'Оқушы'), ('TEACHER', 'Педагог'), ('MANAGER', 'Менеджер')], default='Не выбрано', max_length=64, verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
