# Generated by Django 4.2.4 on 2023-08-20 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_usertype_user_remove_account_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Язык')),
            ],
        ),
        migrations.RemoveField(
            model_name='institution',
            name='students',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='teachers',
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='institution',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Год основания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='institution',
            name='license_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер лиценизии'),
        ),
        migrations.AddField(
            model_name='institution',
            name='ownership',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STATE', 'Государственная'), ('PRIVATE', 'Частная')], default='Не выбрано', max_length=255, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='institution',
            name='school_view',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('GENERAL', 'Государственная'), ('LYCEUM', 'Лицей')], default='Не выбрано', max_length=255, verbose_name='Вид'),
        ),
        migrations.AddField(
            model_name='institution',
            name='slope',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('TECH', 'Технические'), ('HUMAN', 'Гуманитарные')], default='Не выбрано', max_length=255, verbose_name='Уклон'),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='institution',
            name='ln',
            field=models.ManyToManyField(blank=True, to='accounts.language', verbose_name='Язык обучения'),
        ),
    ]
