# Generated by Django 4.2.4 on 2023-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_language_remove_institution_students_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default=1, max_length=64, verbose_name='Ключ языка'),
            preserve_default=False,
        ),
    ]
