# Generated by Django 4.2.4 on 2023-08-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_profile'),
        ('accounts', '0016_alter_institution_school_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('class_level', models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('TECH', 'Технические'), ('HUMAN', 'Гуманитарные')], default='Не выбрано', verbose_name='Уровень класса')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institution', verbose_name='Учереждение')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('subjects', models.ManyToManyField(blank=True, to='products.product', verbose_name='Предметы')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
