# Generated by Django 4.2.4 on 2023-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_institution_owner_classgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': 'Класс/Группа', 'verbose_name_plural': 'Классы/Группы'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_fill',
            field=models.BooleanField(default=False, verbose_name='Аккаунт заполнено'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='class_level',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5), ('SIX', 6), ('SEVEN', 7), ('EIGHT', 8), ('NINE', 9), ('TEN', 10), ('ELEVEN', 11)], default='Не выбрано', verbose_name='Уровень класса'),
        ),
    ]
