# Generated by Django 4.2.4 on 2023-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_classgroup_options_alter_account_account_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='direction',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('IT', 'Информационные технологии')], default='Не выбрано', max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SCHOOL', 'Школа'), ('STUDY_CENTER', 'Учебный центр'), ('COMMUNITY', 'Сообщество')], default='Не выбрано', max_length=255, verbose_name='Тип учреждение'),
        ),
    ]
