# Generated by Django 4.2.4 on 2023-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_institution_direction_alter_institution_inst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/institution/images/', verbose_name='Изображение'),
        ),
    ]
