# Generated by Django 4.2.4 on 2023-09-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_question_body'),
        ('accounts', '0020_institution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='flow',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('ONE', 1), ('TWO', 2), ('THREE', 3)], default='Не выбрано', verbose_name='Поток'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='Программы'),
        ),
    ]
