# Generated by Django 4.2.4 on 2023-09-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_classgroup_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('SCHOOL', 'Школа'), ('COMMUNITY', 'Сообщество')], default='Не выбрано', max_length=255, verbose_name='Тип учреждение'),
        ),
    ]
