# Generated by Django 4.2.4 on 2023-10-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_institution_inst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='direction',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('IT', 'Информационные технологии'), ('GENERAL_EDU', 'Общее образование')], default='Не выбрано', max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('STUDENT', 'Студент'), ('TEACHER', 'Педагог'), ('MANAGER', 'Менеджер')], default='Не выбрано', max_length=64, verbose_name='Тип'),
        ),
    ]
