# Generated by Django 4.2.4 on 2024-04-04 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('slug', models.SlugField(max_length=64, verbose_name='Key')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Title')),
                ('course_type', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='Free', max_length=40, verbose_name='Course type')),
                ('course_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Course price')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='products/posters/', verbose_name='Poster')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('all_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='All rating')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('course_authors', models.ManyToManyField(blank=True, related_name='course_authors', to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('ln', models.ManyToManyField(blank=True, to='main.language', verbose_name='Languages')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='main.subcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('-date_created',),
            },
        ),
    ]
