# Generated by Django 4.2.4 on 2024-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subscribe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
    ]
