# Generated by Django 4.2.4 on 2024-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_name_kk_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='main/course/posters/', verbose_name='Poster'),
        ),
    ]
