# Generated by Django 4.2.4 on 2024-04-04 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_course_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User course',
                'verbose_name_plural': 'User courses',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lesson', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercourse', verbose_name='User course')),
            ],
            options={
                'verbose_name': 'User lesson',
                'verbose_name_plural': 'User lessons',
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter', verbose_name='Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapter', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercourse', verbose_name='User course')),
            ],
            options={
                'verbose_name': 'User chapter',
                'verbose_name_plural': 'User chapters',
            },
        ),
    ]
