# Generated by Django 4.2.4 on 2024-04-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usercourse_userlesson_userchapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlesson',
            options={'ordering': ('lesson__index',), 'verbose_name': 'User lesson', 'verbose_name_plural': 'User lessons'},
        ),
    ]
