# Generated by Django 4.2.4 on 2024-08-12 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_userlesson_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChapter',
            new_name='OldUserChapter',
        ),
        migrations.RenameModel(
            old_name='UserCourse',
            new_name='OldUserCourse',
        ),
        migrations.RenameModel(
            old_name='UserLesson',
            new_name='OldUserLesson',
        ),
    ]
