# Generated by Django 4.2.4 on 2024-08-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_userchapter_olduserchapter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olduserchapter',
            options={'verbose_name': 'Old User chapter', 'verbose_name_plural': 'Old User chapters'},
        ),
        migrations.AlterModelOptions(
            name='oldusercourse',
            options={'verbose_name': 'Old User course', 'verbose_name_plural': 'Old User courses'},
        ),
        migrations.AlterModelOptions(
            name='olduserlesson',
            options={'ordering': ('lesson__index',), 'verbose_name': 'Old User lesson', 'verbose_name_plural': 'Old User lessons'},
        ),
    ]
