# Generated by Django 4.2.4 on 2024-08-12 15:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_olduserchapter_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='OldRating',
        ),
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='OldSubscribe',
        ),
        migrations.AlterModelOptions(
            name='oldrating',
            options={'verbose_name': 'Old Rating', 'verbose_name_plural': 'Old Ratings'},
        ),
        migrations.AlterModelOptions(
            name='oldsubscribe',
            options={'verbose_name': 'Old Subscribe', 'verbose_name_plural': 'Old Subscribes'},
        ),
    ]
