# Generated by Django 4.2.4 on 2024-08-12 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_rename_rating_oldrating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='OldArticle',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='OldCategory',
        ),
        migrations.RenameModel(
            old_name='Chapter',
            new_name='OldChapter',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='OldCourse',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='OldLanguage',
        ),
        migrations.RenameModel(
            old_name='Lesson',
            new_name='OldLesson',
        ),
        migrations.RenameModel(
            old_name='Purpose',
            new_name='OldPurpose',
        ),
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='OldSubCategory',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='OldVideo',
        ),
        migrations.AlterModelOptions(
            name='oldarticle',
            options={'verbose_name': 'Old Article', 'verbose_name_plural': 'Old Articles'},
        ),
        migrations.AlterModelOptions(
            name='oldcategory',
            options={'ordering': ('name',), 'verbose_name': 'Old Category', 'verbose_name_plural': 'Old Categories'},
        ),
        migrations.AlterModelOptions(
            name='oldchapter',
            options={'verbose_name': 'Old Chapter', 'verbose_name_plural': 'Old Chapters'},
        ),
        migrations.AlterModelOptions(
            name='oldcourse',
            options={'ordering': ('-date_created',), 'verbose_name': 'Old Course', 'verbose_name_plural': 'Old Courses'},
        ),
        migrations.AlterModelOptions(
            name='oldlanguage',
            options={'verbose_name': 'Old Language', 'verbose_name_plural': 'Old Languages'},
        ),
        migrations.AlterModelOptions(
            name='oldlesson',
            options={'verbose_name': 'Old Lesson', 'verbose_name_plural': 'Old Lessons'},
        ),
        migrations.AlterModelOptions(
            name='oldpurpose',
            options={'verbose_name': 'Old Purpose', 'verbose_name_plural': 'Old Purposes'},
        ),
        migrations.AlterModelOptions(
            name='oldsubcategory',
            options={'ordering': ('name',), 'verbose_name': 'Old Subcategory', 'verbose_name_plural': 'Old Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='oldvideo',
            options={'verbose_name': 'Old Video', 'verbose_name_plural': 'Old Videos'},
        ),
    ]
