# Generated by Django 4.2.4 on 2024-08-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cloneuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('USER', 'User'), ('AUTHOR', 'Author'), ('LLP', 'Limited Liability Partnership')], default='User', max_length=64, verbose_name='Account type')),
                ('id_number', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID number account')),
                ('specialty', models.CharField(blank=True, max_length=64, null=True, verbose_name='Specialty')),
                ('city', models.CharField(choices=[('NOT_DEFINED', 'Not selected'), ('SHYMKENT', 'Шымкент'), ('ALMATY', 'Алматы'), ('ASTANA', 'Астана')], default='Not selected', max_length=64, verbose_name='City')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('about', models.TextField(blank=True, max_length=120, null=True, verbose_name='About')),
                ('account_fill', models.BooleanField(default=False, verbose_name='Is filled out')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.cloneuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Clone Account',
                'verbose_name_plural': 'Clone Accounts',
            },
        ),
    ]
