# Generated by Django 4.2.4 on 2024-08-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_cloneaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcourse',
            name='course_authors',
            field=models.ManyToManyField(blank=True, related_name='course_authors', to='main.cloneuser', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='oldrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='main.cloneuser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='oldsubscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user', to='main.cloneuser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='olduserchapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapter', to='main.cloneuser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='oldusercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='main.cloneuser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='olduserlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lesson', to='main.cloneuser', verbose_name='User'),
        ),
    ]
