# Generated by Django 5.1 on 2024-08-16 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0003_category_name_en_category_name_kk_category_name_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('completion_percentage', models.FloatField(default=0.0, verbose_name='Completion percentage')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_user_courses', to='resources.course', verbose_name='Course')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.lesson', verbose_name='Current lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_user_courses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User course',
                'verbose_name_plural': 'User courses',
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('completion_percentage', models.FloatField(default=0.0, verbose_name='Completion percentage')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch_user_chapters', to='resources.chapter', verbose_name='Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_user_chapters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_user_chapters', to='workspace.usercourse', verbose_name='User course')),
            ],
            options={
                'verbose_name': 'User chapter',
                'verbose_name_plural': 'User chapters',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.PositiveIntegerField(default=0, verbose_name='Current position')),
                ('is_started', models.BooleanField(default=False, verbose_name='Is started')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_user_lessons', to='resources.lesson', verbose_name='Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_user_lessons', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_user_lessons', to='workspace.usercourse', verbose_name='User course')),
            ],
            options={
                'verbose_name': 'Old User lesson',
                'verbose_name_plural': 'Old User lessons',
                'ordering': ('lesson__order',),
            },
        ),
    ]
