# Generated by Django 5.1 on 2024-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlesson',
            options={'ordering': ('lesson__order',), 'verbose_name': 'User lesson', 'verbose_name_plural': 'User lessons'},
        ),
    ]
