# Generated by Django 4.2.4 on 2023-08-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='finish',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Концовка'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Текущий'),
        ),
    ]
