# Generated by Django 4.2.4 on 2024-01-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.AddField(
            model_name='article',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Duration (min)'),
        ),
    ]
