# Generated by Django 4.2.4 on 2023-08-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_lesson_finish_remove_lesson_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='Задание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('WRITE', 'Материальные задачи'), ('QUIZ', 'Тест')], default='Материальные задачи', max_length=255, verbose_name='Тип задачи'),
        ),
    ]
