# Generated by Django 4.2.4 on 2024-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_name_kk_category_name_ru_topic_name_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_headline',
            field=models.BooleanField(default=False, verbose_name='Headline'),
        ),
    ]
