# Generated by Django 4.2.4 on 2023-08-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
