# Generated by Django 4.2.4 on 2024-01-17 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_course_all_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='all_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='All rating'),
        ),
    ]
