# Generated by Django 4.2.4 on 2024-01-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_course_date_created_alter_course_all_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('date_created',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
