# Generated by Django 4.2.4 on 2023-08-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='class_level',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не выбрано'), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5), ('SIX', 6), ('SEVEN', 7), ('EIGHT', 8), ('NINE', 9), ('TEN', 10), ('ELEVEN', 11)], default='Не выбрано', verbose_name='Уровень класса'),
        ),
    ]
