# Generated by Django 4.2.4 on 2023-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='item',
            field=models.TextField(blank=True, null=True, verbose_name='Цель обучение'),
        ),
    ]
