# Generated by Django 4.2.4 on 2024-01-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_course_options_alter_course_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-date_created',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
