# Generated by Django 4.2.4 on 2023-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О разделе'),
        ),
    ]
