# Generated by Django 4.2.4 on 2024-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_course_is_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_headline',
            field=models.BooleanField(default=False, verbose_name='Headline'),
        ),
    ]
