# Generated by Django 4.2.4 on 2024-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_course_is_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='products/posters/', verbose_name='Poster'),
        ),
    ]
