# Generated by Django 4.2.4 on 2023-08-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_chapter_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Тело вопроса'),
        ),
    ]
