# Generated by Django 4.2.4 on 2024-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_course_image_alter_course_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='all_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='All rating'),
        ),
    ]
