# Generated by Django 4.2.4 on 2024-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Duration (min)'),
        ),
    ]
