# Generated by Django 4.2.4 on 2024-02-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_video_url_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Index'),
        ),
    ]
