# Generated by Django 4.2.4 on 2024-03-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_alter_lesson_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='Free', max_length=40, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Course price')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.course', verbose_name='Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
            },
        ),
    ]
