# Generated by Django 4.2.4 on 2024-03-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_course_course_type_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Course price'),
        ),
    ]
