# Generated by Django 4.2.4 on 2024-03-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_course_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='view',
        ),
    ]
