# Generated by Django 4.2.4 on 2024-03-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_chapter_about_chapter_chapter_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_headline',
        ),
    ]
