# Generated by Django 4.2.4 on 2024-03-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_course_is_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='Last update'),
        ),
    ]
