# Generated by Django 4.2.4 on 2024-03-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_course_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
